### ISSUE TITLE
Contractions marked as mispellings

### ISSUE THREAD

**Issue by dbolton** [cfinke/Typo.js#11]
```javascript
var dictionary = new Typo("en_US", affData, dicData);
var is_spelled_correctly = dictionary.check("aren't") //should be true, but returns false
```

All contractions appear to fail, e.g. "I'm", "we're", "didn't", etc.

**Comment by cfinke** [comment]
After many years of thought, I am going to close this as WONTFIX. Curly quotes are typographical decoration and out of scope of this hobby spellchecker.
