### ISSUE TITLE
Add a demo page

### ISSUE THREAD

**Issue by yairEO** [cfinke/Typo.js#27]
please add a demo page to the repository and also a link to a live version, it will save people time to download and test it themselves. maybe it's not exactly what they were looking for or whatever.

**Comment by oyeanuj** [comment]
+1 to this. It would really aid in how it actually works.

**Comment by laduran** [comment]
+1

Yep. Can't tell how to use this library but would like to be able to use it.

**Comment by cfinke** [comment]
I've added a live demo at http://www.chrisfinke.com/files/typo-demo/ and a Node.js example file at https://github.com/cfinke/Typo.js/blob/master/examples/node/index.js
