### ISSUE TITLE
`typo.suggest("hostipal")` gives `["h01stipal", "h21stipal", "h31stipal", "h41stipal", "h51stipal"]` (expected `["hospital"]`)

### ISSUE THREAD

**Issue by lionel-rowe** [cfinke/Typo.js#87]
With the `en_US` dictionaries loaded, `typo.suggest("hostipal")` gives the nonexistent `["h01stipal", "h21stipal", "h31stipal", "h41stipal", "h51stipal"]`, none of which are specified as words in the `dic` file.

Expected results to include `"hospital"`.

Similar results can be obtained with `extremelylongwordthatdoesntexist` and `antidixestablishmentarianism` (both of which also hang for a really long time before returning the incorrect results):

```
[
  "extremelylongw03rdthatdoesntexist",
  "extremelylongw23rdthatdoesntexist",
  "extremelylongw33rdthatdoesntexist",
  "extremelylongw43rdthatdoesntexist",
  "extremelylongw53rdthatdoesntexist"
]
Typo: extremelylongwordthatdoesntexist: 38241ms
[
  "antidisestablishmentarianism",
  "antidix01stablishmentarianism",
  "antidix21stablishmentarianism",
  "antidix31stablishmentarianism",
  "antidix41stablishmentarianism"
]
Typo: antidixestablishmentarianism: 26839ms
```

**Comment by lionel-rowe** [comment]
Looks like it's due to a bug in `checkExact` and `compoundRules`. The "words" being matched all contain ordinal numbers (1st, 21st, 31st..., 3rd, 23rd, 33rd...). Meanwhile, `compoundRules` for the `en_US` dictionary are parsed to the following:

```ts
[
  /(0|1|2|3|4|5|6|7|8|9)*(1)(0th|1th|2th|3th|4th|5th|6th|7th|8th|9th)/i,
  /(0|1|2|3|4|5|6|7|8|9)*(0|2|3|4|5|6|7|8|9)(0th|1st|2nd|3rd|4th|5th|6th|7th|8th|9th)/i
]
```

I think the regexes aren't quite correct even internally, as they match `01st` but not `1st`; but more importantly for this bug, they match anywhere within the word, not just whole words. Wrapping in `/^(?:...)$/` should fix that.

**Comment by cfinke** [comment]
Thanks, I'll address this ASAP.

**Comment by cfinke** [comment]
I've pushed e4cc9899ea25cca4e9d34d5910f4fb318af180f3 which fixes the `hostipal` issue. Thanks!
